---
name: Validate Configurations

on:
  workflow_call:

jobs:
  config-validation: #test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get config.yml files
        run: |
          #!/bin/bash

          # Define color codes
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          CYAN='\033[0;36m'
          NC='\033[0m' # No Color
          ITALIC='\033[3m'
          BOLD='\033[1m'
          YELLOW='\033[1;33m'
          LIGHT_GREEN='\033[1;32m'
          LIGHT_RED='\033[1;31m'
          MAGENTA='\033[1;35m'

          echo -e "\n${BOLD}Hello from ${CYAN}${BOLD}validate-config.yml!${NC} \xF0\x9F\x91\x8B \n"
          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"

          echo -e "🚀 ${YELLOW}${BOLD}[Step 1]: ${NC}${BOLD}Running ${LIGHT_GREEN}${ITALIC}${BOLD}validation script${NC} 🔄"
          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"

          # Debug: Show current directory
          #echo -e "Current directory: $(pwd)\n"

          root=$(pwd)

          # Find colconfig.yaml files
          find . -name "colconfig.yaml" > files.txt

          # Debug: Show contents of files.txt
          echo -e "Files found:\n$(cat files.txt)\n"

          counter=0
          total_files=0

          while read -r line; do
              echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
              dir=$(dirname "$line")
              cd $dir
              output=$(docker run -v $(pwd):/config ghcr.io/liatrio/liatrio-otel-collector:latest-amd64 validate --config /config/colconfig.yaml 2>&1 || true)
              if echo "$output" | grep -q "Error:"; then
                  echo -e "❌ ${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed ${NC}${BOLD}for ${YELLOW}${ITALIC}$dir/config.yaml${NC}\n"
                  echo -e "${output}\n"
                  counter=$((counter+1))
                  total_files=$((total_files+1))
              else
                echo -e "✅ ${BOLD}Validation ${LIGHT_GREEN}${BOLD}${ITALIC}succeeded ${NC}${BOLD}for ${YELLOW}${ITALIC}$dir${NC}"
                total_files=$((total_files+1))
              fi
              cd $root
          done < files.txt

          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"


          if((counter>0)); then
              echo -e "🚨 ${NC}${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed ${NC}${BOLD}for ${LIGHT_RED}${BOLD}${ITALIC}$counter${NC}${BOLD}/$total_files configurations! 🚨\n"
              exit 1
          else
              echo -e "✅ ${BOLD}All configurations are ${LIGHT_GREEN}${BOLD}${ITALIC}valid! 🎉\n"
          fi
          exit 0